### ISSUE TITLE
Elevation data support

### ISSUE THREAD

**Issue by VladimirMorozov** [intgr/histonia#1]
Would it be possible to support lidar wms too? This would allow to map paths in forests where gps is not very accurate and the ground is hidden behind trees with great detail.

https://geoportaal.maaamet.ee/index.php?lang_id=1&page_id=508

**Comment by intgr** [comment]
Should be, yes. Feel free to ping me again in a few days if I forget.

**Comment by intgr** [comment]
There are two maps made from the LIDAR survey: terrain and surface models.

Digital Terrain Model (DTM) - represents the bare ground surface without any objects like plants and buildings:

![image](https://raw.githubusercontent.com/intgr/static/master/histonia/histonia-terrain-01.png)

DTM together with the Digital Surface Model (DSM) overlay - captures both the natural and built/artificial features of the environment:

![image](https://raw.githubusercontent.com/intgr/static/master/histonia/histonia-terrain-surface-01.png)

Is this what you were looking for?

Right now I kept the roads & place names layers as well, like X-GIS displays it. Not sure if they are helpful or distracting, I can remove them as well, let me know.

**Comment by VladimirMorozov** [comment]
DTM without DSM is what I thought would be most helpful. You can usually see trees with aerial imagery, but cannot see ground underneath. As for roads and places - I don't think they would obstruct much of the terrain, on the contrary they will help to find the place on the map.

**Comment by intgr** [comment]
I kept both DTM and DSM options and documented the usage in README (https://github.com/intgr/histonia#lidar-maps). Let me know if you run into any issues.
