### ISSUE TITLE
Tile service URLs have changed

### ISSUE THREAD

**Issue by VladimirMorozov** [intgr/histonia#3]
I've managed to make it work by setting aerophoto URL to https://kaart.maaamet.ee/wms/fotokaart? and terrain and surface URLs to https://xgis.maaamet.ee/xgis2/service/1h00/mit?

I'm not sure how stable this URL https://xgis.maaamet.ee/xgis2/service/1h00/mit? is. I took it from Maa-amet's browser app. Is there a way to use official WMS service?

**Comment by intgr** [comment]
Thanks for letting me know

> Is there a way to use official WMS service?

I tried it way back, unfortunately I couldn't get it to work with mapproxy, that's why I took the URL used by the web app.

**Comment by intgr** [comment]
I have fixed the URLs, thanks again
